name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8]

    container: 
      image: sammorleyshort/pynauty:py${{ matrix.python-version }}-slim
    steps:
    - name: Install PyNauty
      run: |
        cd /usr/src/pynauty
        make pynauty
        make user-ins
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -e .
        which python
        python -V
        which pip
        pip list
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
